# Generated by Django 4.2.30 on 2026-06-22 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "words_learned",
                    models.IntegerField(default=0, verbose_name="学习单词数"),
                ),
                (
                    "words_reviewed",
                    models.IntegerField(default=0, verbose_name="复习单词数"),
                ),
                ("quiz_count", models.IntegerField(default=0, verbose_name="测验次数")),
                (
                    "study_minutes",
                    models.IntegerField(default=0, verbose_name="学习时长(分钟)"),
                ),
                (
                    "checked_in",
                    models.BooleanField(default=False, verbose_name="是否打卡"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "daily_progress",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
