# Generated by Django 4.2.30 on 2026-06-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="标题")),
                (
                    "title_cn",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="中文标题"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        default="EnglishGo",
                        max_length=100,
                        verbose_name="作者",
                    ),
                ),
                ("content", models.TextField(verbose_name="正文（英文）")),
                (
                    "content_cn",
                    models.TextField(blank=True, default="", verbose_name="中文翻译"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, default="", verbose_name="摘要"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "入门"),
                            ("intermediate", "中级"),
                            ("advanced", "高级"),
                        ],
                        default="intermediate",
                        max_length=20,
                        verbose_name="难度",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="标签（逗号分隔）",
                    ),
                ),
                ("word_count", models.IntegerField(default=0, verbose_name="字数")),
                ("read_count", models.IntegerField(default=0, verbose_name="阅读次数")),
                (
                    "source_url",
                    models.URLField(blank=True, default="", verbose_name="来源链接"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "db_table": "article",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["level"], name="article_level_5c3a08_idx"),
                    models.Index(
                        fields=["-created_at"], name="article_created_06aad0_idx"
                    ),
                ],
            },
        ),
    ]
