# Generated by Django 4.2.30 on 2026-06-22 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quiz_type",
                    models.CharField(
                        choices=[
                            ("choice", "选择题"),
                            ("spelling", "拼写题"),
                            ("listening", "英译中"),
                        ],
                        max_length=20,
                        verbose_name="测验类型",
                    ),
                ),
                (
                    "total_questions",
                    models.IntegerField(default=0, verbose_name="总题数"),
                ),
                (
                    "correct_answers",
                    models.IntegerField(default=0, verbose_name="正确数"),
                ),
                ("score", models.FloatField(default=0, verbose_name="得分")),
                (
                    "completed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="完成时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quiz_record",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_id", models.IntegerField(verbose_name="单词ID")),
                ("question", models.CharField(max_length=500, verbose_name="题目")),
                (
                    "correct_answer",
                    models.CharField(max_length=500, verbose_name="正确答案"),
                ),
                (
                    "user_answer",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="用户答案"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="是否正确"),
                ),
                (
                    "quiz_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="quiz.quizrecord",
                    ),
                ),
            ],
            options={
                "db_table": "quiz_detail",
            },
        ),
    ]
