# Generated by Django 4.2.30 on 2026-06-22 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english", models.CharField(max_length=200, verbose_name="英文")),
                ("chinese", models.CharField(max_length=200, verbose_name="中文释义")),
                (
                    "phonetic",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="音标"
                    ),
                ),
                (
                    "part_of_speech",
                    models.CharField(
                        choices=[
                            ("noun", "名词"),
                            ("verb", "动词"),
                            ("adjective", "形容词"),
                            ("adverb", "副词"),
                            ("preposition", "介词"),
                            ("conjunction", "连词"),
                            ("pronoun", "代词"),
                            ("phrase", "短语"),
                        ],
                        default="noun",
                        max_length=20,
                        verbose_name="词性",
                    ),
                ),
                (
                    "example",
                    models.TextField(blank=True, default="", verbose_name="例句"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("basic", "基础"),
                            ("intermediate", "中级"),
                            ("advanced", "高级"),
                            ("business", "商务"),
                            ("travel", "旅游"),
                        ],
                        default="basic",
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(default=1, verbose_name="难度(1-5)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "db_table": "word",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["category"], name="word_categor_248f8d_idx"),
                    models.Index(fields=["difficulty"], name="word_difficu_fd7688_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="是否收藏"),
                ),
                (
                    "mastered",
                    models.BooleanField(default=False, verbose_name="是否掌握"),
                ),
                (
                    "practice_count",
                    models.IntegerField(default=0, verbose_name="练习次数"),
                ),
                (
                    "correct_count",
                    models.IntegerField(default=0, verbose_name="正确次数"),
                ),
                (
                    "last_practiced",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后练习时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_words",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_words",
                        to="vocabulary.word",
                    ),
                ),
            ],
            options={
                "db_table": "user_word",
                "unique_together": {("user", "word")},
            },
        ),
    ]
