# Generated by Django 4.2.30 on 2026-06-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="category",
            field=models.CharField(
                choices=[
                    ("basic", "基础"),
                    ("intermediate", "中级"),
                    ("advanced", "高级"),
                    ("business", "商务"),
                    ("travel", "旅游"),
                    ("junior", "初中"),
                    ("senior", "高中"),
                    ("cet4", "四级"),
                    ("cet6", "六级"),
                    ("postgraduate", "考研"),
                    ("toefl", "托福"),
                    ("sat", "SAT"),
                ],
                default="basic",
                max_length=20,
                verbose_name="分类",
            ),
        ),
    ]
